language: cpp
sudo: required
dist: trusty

before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -q

install:
    - sudo apt-get install -y flex bison doxygen graphviz libboost-all-dev liblog4cxx10-dev
    - sudo apt-get install -y gcc-4.9
    - sudo apt-get install -y clang-3.5 libclang-common-3.5-dev libclang-3.5-dev libclang1-3.5 libllvm3.5 llvm-3.5 llvm-3.5-dev llvm-3.5-runtime

before_script:
    - which llvm-config
    - llvm-config --version
    - which llvm-config-3.5
    - llvm-config-3.5 --version

script: ./waf configure build

compiler:
    - clang
    - gcc-4.9
