language: cpp
before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
    - echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -q

install:
    - sudo apt-get install -y flex bison doxygen libboost-all-dev liblog4cxx10-dev
    - sudo apt-get install -y clang-3.6 libclang-common-3.6-dev libclang-3.6-dev libclang1-3.6 libllvm3.6 llvm-3.6 llvm-3.6-dev llvm-3.6-runtime

script: ./waf configure build

compiler:
    - clang
    - gcc
